### ISSUE TITLE
How to change the param from "p" to "page"

### ISSUE THREAD

**Issue by amitaibu** [pbrisbin/yesod-paginator#12]
Probably a newbie question - but I'd prefer my param to be called `page` -- How would I change `getCurrentPage` to accept it (without too much duplication)?

**Comment by pbrisbin** [comment]
Hmm. Unfortunately, I didn't foresee that requirement and the code's not very amenable to it right now. I would probably start by trying to generalize `PageWidget` (the configuration point for the view-level stuff) to something like `PaginationConfig`. Then that'd be a good place to set the parameter name.

**Comment by amitaibu** [comment]
In that case, can't we just add `param` property to PageWidgetConfig? and set a default value `p` in `defaultPageWidgetConfig`?

**Comment by pbrisbin** [comment]
That value is not currently passed to `getCurrentPage` so you'd have to do that. Also "param" has nothing to do with the widget, hence my suggested rename to `PaginationConfig`. Other than that though, yes, that's what I was picturing -- I just didn't think it was easy enough to qualify as "just".

**Comment by amitaibu** [comment]
I'll get my hands dirty and give it a shot.

> hence my suggested rename to PaginationConfig

Just to clarify - you mean rename `PageWidgetConfig` to `PaginationConfig` and make sure its passed to `getCurrentPage` ? 

>  I just didn't think it was easy enough to qualify as "just".

Funnily enough when I started writing the comment I  wrapped _just_ with quotes myself; Non-verbal comments are always missing the right tone :wink:

**Comment by pbrisbin** [comment]
> Just to clarify - you mean rename PageWidgetConfig to PaginationConfig and make sure its passed to getCurrentPage

Yup. Though `PaginationConfig` is just an armchair suggestion, you should go with whatever makes sense to you. My main concern is that generally this library mixes data logic (getting the right records, paging it) and UI logic (how the widget is displayed). The fact that the configuration point is called Page*Widget*Config is an example of that problem that could (should?) be corrected as part of this.

> Funnily enough when I started writing the comment I wrapped just with quotes myself; Non-verbal comments are always missing the right tone :wink:

Haha, indeed. Thank you for taking the time to dig into this library; I no longer use it in any projects myself, so it's in desperate need of some gardening.

**Comment by amitaibu** [comment]
Awesome, I'll give it a try. Still a newbie in Yesod... :)

**Comment by pbrisbin** [comment]
Closing as stale. Feel free to open a PR (even of partial work) if you want to discuss this feature more.

**Comment by eahlberg** [comment]
@pbrisbin hey! I’m implementing pagination in a Yesod app where I need to use another parameter name for the page number and I saw this stale issue. Are you still open to a PR? If so I could give this a try.

**Comment by pbrisbin** [comment]
I am open to a PR, feel free!

For what it's worth, I've also been using (and contributing to) [yesod-page-cursor](https://github.com/eborden/yesod-page-cursor). It would be a different approach (cursor based), with it's own usage and trade-offs, so I don't consider this project deprecated in favor of it, but I do like it and will probably prefer it myself for anything going forward.

**Comment by eahlberg** [comment]
I see, thanks for the pointer! For my case I think this package would do the job just fine so I opened a PR [here](https://github.com/pbrisbin/yesod-paginator/pull/33).
